name: Generate Termux Sources

on:
  workflow_dispatch:
    inputs:
      type:
        description: "Specify the Termux project to fork [f-droid, play-store]. Defaults to f-droid."
        required: false
        default: "f-droid"

jobs:
  generate:
    runs-on: ubuntu-24.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set --type
        if: "${{ github.event.inputs.type != '' }}"
        run: echo "APP_TYPE=--app-type ${{ github.event.inputs.type }}" >> $GITHUB_ENV

      - name: Generate Sources
        run: |
          chmod +x scripts/generate-sources.sh
          ./scripts/generate-sources.sh $APP_TYPE

      - name: Upload source package
        uses: actions/upload-artifact@v4.6.0
        with:
          name: termux-app-sources
          path: output/termux-app/
          retention-days: 30